import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "styles/globals.css";
import { Box } from "@mui/material";
import Sidebar from "components/layout/sidebar";
import Header from "components/layout/header";
import { Colors } from "styles/theme/color";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Box
      sx={{
        display: "flex",
        height: "100vh",
        width: "100%",
        backgroundColor: Colors.grey,
      }}
    >
      <Sidebar />
      <Box
        sx={{
          display: "flex",
          flexDirection: "column",
          marginLeft: "256px",
          padding: "16px 24px",
          width: "100%",
          height: "100%",
        }}
      >
        <Header />
        {children}
      </Box>
    </Box>
  );
}
